### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by agmeag22** [00198216/FindMyProduct_BackEnd#2]
Conection to the websocket cannot be established.
Errors obtained:
request origin not allowed
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE:websocket

**Comment by Sortweste** [comment]
Check your config properties:

```Ruby
config.cache_classes = true
config.web_socket_server_url = 'wss://URL'
config.action_cable.url = 'wss://URL'
config.action_cable.disable_request_forgery_protection = true
```
